# Streamlit secrets template
# Copy this file to .streamlit/secrets.toml and add your real keys there.

# Google API key for Google Generative AI / Gemini
# Get this from Google Cloud Console and keep it secret.
GOOGLE_API_KEY = "your_google_api_key_here"

# PROMPT used to instruct the model. You can customize it to change how the analysis is generated.
PROMPT = "Provide a structured analysis comparing the resume to the job description. Include a match percentage, key strengths, gaps, and suggested improvements."