GOOGLE_API_KEY="AIzaSyADjbyMnlLMeIIMWiYXrMGBGd_6Ih4Zd2k"
PROMPT = "Analyze the resume and job description, compare skills, experience, and education, and provide a match percentage. aslo tell strength of candidate and potential weakness "